"""add name column to table

Revision ID: f1427810aa46
Revises: 369179342590
Create Date: 2023-09-05 13:01:10.747975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1427810aa46'
down_revision: Union[str, None] = '369179342590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_foreign_key(None, 'reviews', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_column('restaurants', 'name')
    # ### end Alembic commands ###
